version: '3'

services:
  rtsp-server:
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"
    environment:
      - RTSP_PROTOCOLS=tcp
      - NAME=rtsp_simple_server
  camera:
    build:
      context: .
    command: >
      sh -c "python3 ./stream.py"
    volumes:
      - ./:/camera
